export const ROLES = {
  ADMIN: "ADMIN",
  DOCTOR: "DOCTOR",
  RECEPTIONIST: "RECEPTIONIST",
  TECHNICIAN: "TECHNICIAN",
  PHARMACIST: "PHARMACIST",
  PATIENT: "PATIENT",
};

export const ROLE_PREFIX = "ROLE_";
