export const ROUTES = {
  LOGIN: "/login",
  ADMIN_HOME: "/admin",
  ADMIN_DEPARTMENTS: "/admin/departments",
  ADMIN_STAFF: "/admin/staff",
  ADMIN_SCHEDULES: "/admin/schedules",
  DOCTOR_HOME: "/doctor",
  DOCTOR_VISIT_QUEUE: "/doctor/queue",
  DOCTOR_VISIT_DETAILS: "/doctor/visits/:id",
  RECEPTION_HOME: "/reception",
  PHARMACY_HOME: "/pharmacy",
  LAB_HOME: "/lab",
  PATIENT_HOME: "/patient",
  RECEPTION_PATIENTS: "/reception/patients",
  RECEPTION_QUEUE: "/reception/queue",
};
